// SPDX-FileCopyrightText: Copyright (c) 2026 Wataru Ashihara <wataash0607@gmail.com>
// SPDX-License-Identifier: Apache-2.0
import { expect, test } from '@playwright/test';
import { closeLibrary, importLink, openLibrary } from './helpers';
import { scramble } from '@web-music/ireal';

for (const width of [320, 1000]) test(`library controls and import dialog at ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 });
  await page.goto('/');
  await expect(page.getByLabel('Search songs')).not.toBeVisible();
  await openLibrary(page);
  const trigger = page.getByRole('button', { name: 'Add chart', exact: true });
  await trigger.click();
  const dialog = page.getByRole('dialog', { name: 'Add chart' });
  await expect(dialog).toBeVisible();
  if (width === 320) {
    await page.keyboard.press('Escape');
    await expect(dialog).not.toBeVisible();
    await expect(trigger).toBeFocused();
    await trigger.click();
  }
  await page.getByLabel('Shared link / HTML').fill('irealb://' + encodeURIComponent('Evening Practice with a Very Long Song Title=Example Composer==Swing=C==1r34LbKcu7' + scramble('[C7XyQ|F7XyQZ') + '==0=0'));
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.locator('.song-title')).toHaveText('Evening Practice with a Very Long Song Title');
  await expect(page.locator('.song-meta')).toHaveText('Example Composer · Swing');
  const heading = page.locator('.song-title');
  expect(await heading.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
  const titleBox = (await heading.boundingBox())!;
  const keyBox = (await page.getByLabel('Song key', { exact: true }).boundingBox())!;
  expect(keyBox.y).toBeGreaterThan(titleBox.y + titleBox.height);
  await expect(page.getByRole('dialog', { name: 'Choose song', exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath(`song-library-${width}.png`) });
  await closeLibrary(page);
  expect(await page.locator('[data-chord-practice]').evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(2);
  if (width !== 320) return;
  await page.getByText('Full chart', { exact: true }).click();
  await expect(page.locator('.full-score h3')).toHaveCount(0);
  await expect(page.getByRole('group', { name: 'Strings for bass notes' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Reset settings and position' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Delete current imported chart' })).toHaveCount(0);
  await openLibrary(page);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Choose song', exact: true })).toBeFocused();
  await expect(page.getByLabel('Search songs')).not.toBeVisible();
  await expect(page.locator('.question-heading').getByRole('button', { name: 'Play chord' })).toBeVisible();
  await page.screenshot({ path: info.outputPath(`library-${width}.png`) });
  await page.getByRole('button', { name: 'Chord practice settings' }).click();
  await page.getByRole('button', { name: /^Instrument and tuning/ }).click();
  const bass = page.getByRole('group', { name: 'Strings for bass notes' });
  await expect(bass).toBeVisible();
  await bass.getByLabel('String 1', { exact: true }).check();
  await page.screenshot({ path: info.outputPath(`instrument-${width}.png`) });
  await page.keyboard.press('Escape');
  await expect(bass).toHaveCount(0);
  await page.getByRole('button', { name: 'Chord practice settings' }).click();
  await page.screenshot({ path: info.outputPath(`settings-${width}.png`) });
  const frets = page.getByRole('group', { name: 'Frets', exact: true });
  await expect(frets).toContainText('24');
  await page.getByRole('button', { name: 'Frets smaller' }).click();
  await expect(frets).toContainText('23');
  await expect(page.getByRole('menuitemcheckbox', { name: 'Sound' })).toBeVisible();
  await page.getByRole('button', { name: /^Instrument and tuning/ }).click();
  await expect(page.getByRole('dialog', { name: 'Settings', exact: true })).not.toBeVisible();
  await expect(bass.getByLabel('String 1', { exact: true })).toBeChecked();
});

test("combines playlist, style, search and favorites", async ({ page }, info) => {
  const width = 320;
  await page.setViewportSize({ width, height: 900 });
  await page.goto('/');
  await openLibrary(page);
  const song = (title: string, style: string) => `${title}=Example==${style}=C==1r34LbKcu7${scramble('[C7XyQZ')}==0=0`;
  for (const [name, charts] of [['Set A', [song('Blue Example', 'Swing'), song('Quiet Example', 'Bossa')]], ['Set B', [song('Red Example', 'Swing')]]] as const) {
    await importLink(page, 'irealb://' + encodeURIComponent([...charts, name].join('===')));
    await expect(page.locator('.song-title')).toHaveText(name === 'Set A' ? 'Blue Example' : 'Red Example');
  }
  const picker = page.getByLabel('Song', { exact: true });
  const results = picker.locator('button:not(:disabled)');
  await page.getByLabel('Playlist', { exact: true }).selectOption('playlist:Set A');
  await expect(results).toHaveCount(2);
  await expect(page.locator('.song-title')).toHaveText('Red Example');
  await picker.getByRole('button', { name: 'Blue Example · Example', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Choose song', exact: true })).not.toBeVisible();
  await page.getByRole('button', { name: 'Add to favorites', exact: true }).click();
  await openLibrary(page);
  await page.getByRole('button', { name: /^Favorites only/ }).click();
  await expect(results).toHaveCount(1);
  await page.getByLabel('Search songs').fill('missing');
  await expect(results).toHaveCount(0);
  await expect(page.getByRole('status').filter({ hasText: 'No matching songs' })).toBeVisible();
  await expect(page.locator('.song-count')).toHaveText('0 songs');
  expect(await page.locator('[data-chord-practice]').evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(2);
  await page.screenshot({ path: info.outputPath(`filters-${width}.png`) });
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
  await expect(page.getByLabel('Playlist', { exact: true })).toHaveValue('');
  await expect.poll(() => results.evaluateAll(nodes => nodes.map(node => node.getAttribute('aria-label')))).toEqual(expect.arrayContaining(['Blue Example · Example', 'Quiet Example · Example', 'Red Example · Example']));
});

test('sorts imported songs without changing selection and copies an importable link', async ({ page, context, browserName }) => {
  test.skip(browserName !== 'chromium', 'Playwright clipboard-read/write permissions are supported only in Chromium.');
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.goto('/');
  await openLibrary(page);
  const song = (title: string, artist: string) => `${title}=${artist}==Swing=C==1r34LbKcu7${scramble('[C7XyQZ')}==0=0`;
  const link = 'irealb://' + encodeURIComponent([song('Zulu test', 'Alpha'), song('Alpha test', 'Zulu'), 'Sort test'].join('==='));
  await importLink(page, link);
  await page.getByLabel('Playlist', { exact: true }).selectOption('playlist:Sort test');
  const picker = page.getByLabel('Song', { exact: true });
  const selected = await picker.getAttribute('data-selected');
  await expect.poll(() => picker.locator('button').evaluateAll(nodes => nodes.map(node => node.getAttribute('aria-label')))).toEqual(['Alpha test · Zulu', 'Zulu test · Alpha']);
  await page.getByLabel('Sort songs').selectOption('artist');
  await expect.poll(() => picker.locator('button').evaluateAll(nodes => nodes.map(node => node.getAttribute('aria-label')))).toEqual(['Zulu test · Alpha', 'Alpha test · Zulu']);
  await page.getByLabel('Sort songs').selectOption('import');
  await expect.poll(() => picker.locator('button').evaluateAll(nodes => nodes.map(node => node.getAttribute('aria-label')))).toEqual(['Zulu test · Alpha', 'Alpha test · Zulu']);
  await expect(picker).toHaveAttribute('data-selected', selected);
  await page.reload();
  await openLibrary(page);
  await page.getByLabel('Playlist', { exact: true }).selectOption('playlist:Sort test');
  await page.getByLabel('Sort songs').selectOption('import');
  await expect.poll(() => picker.locator('button').evaluateAll(nodes => nodes.map(node => node.getAttribute('aria-label')))).toEqual(['Zulu test · Alpha', 'Alpha test · Zulu']);
  await closeLibrary(page);
  await page.getByRole('button', { name: 'Chord practice settings' }).click();
  await page.getByRole('button', { name: 'Export current chart', exact: true }).click();
  await page.getByRole('button', { name: 'Copy song link', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Song link copied');
  const copied = await page.evaluate(() => navigator.clipboard.readText());
  expect(copied).toMatch(/^irealb:\/\//);
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await openLibrary(page);
  await importLink(page, copied);
  await expect(page.locator('.song-title')).toHaveText('Zulu test');
  await page.getByLabel('Playlist', { exact: true }).selectOption('playlist:Sort test');
  await expect(picker.locator('button')).toHaveCount(2);
});

for (const width of [320, 1000]) test(`keeps the view switch fixed at ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 });
  await page.goto('/');
  const toggle = page.getByRole('group', { name: 'View mode', exact: true });
  await expect(page.getByRole('button', { name: 'Choose song', exact: true })).toBeEnabled();
  await expect(toggle).toBeVisible();
  const original = await toggle.boundingBox();
  await toggle.getByRole('button', { name: 'List', exact: true }).click();
  await expect(toggle.getByRole('button', { name: 'List', exact: true })).toHaveAttribute('aria-pressed', 'true');
  expect(await toggle.boundingBox()).toEqual(original);
  await toggle.getByRole('button', { name: 'By section', exact: true }).click();
  await expect(toggle.getByRole('button', { name: 'By section', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(toggle.getByRole('button', { name: 'List', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await expect(page.locator('.chord-list')).toBeVisible();
  expect(await toggle.boundingBox()).toEqual(original);
  await page.screenshot({ path: info.outputPath(`view-switch-${width}.png`) });
  await toggle.getByRole('button', { name: 'Card', exact: true }).click();
  expect(await toggle.boundingBox()).toEqual(original);
});

 test('browses song candidates with the keyboard before selecting', async ({ page }) => {
  await page.goto('/');
  await openLibrary(page);
  const picker = page.getByLabel('Song', { exact: true });
  const selected = await picker.getAttribute('data-selected');
  await page.keyboard.press('Tab');
  await expect(picker.locator('button[aria-pressed="true"]')).toBeFocused();
  await page.keyboard.press('Home');
  await expect(picker.locator('button').first()).toBeFocused();
  await expect(picker).toHaveAttribute('data-selected', selected);
  await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog', { name: 'Choose song', exact: true })).not.toBeVisible();
  await expect(page.locator('.song-title')).toHaveText('Chord extensions');
});
